# Site settings
title:          LittlevGL Blog - News and Tutorials for Embedded GUI Enthusiasts
description:    "Release notes of LittlevGL, Tutorials, Poring guides, Development board and microcontroller test, ideas, tips and tricks and more."

# Google Analytics
google_analytics: UA—78811084-3

# Author
author:
  name:         Gabor Kiss-Vamosi
  email:        kisvegabor@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
